POST http://localhost:39148/eai/sendergebnismeldung
Content-Type: application/json

{
  "id": 123,
  "name": "Testname",
  "age": 99,
  "kind": "Schnellmeldung"
}


###
POST http://localhost:39148/eai/sendergebnismeldung
Content-Type: application/json

{
  "kind": "Sollte Fehler werfen, weil Property 'Name' fehlt",
  "id": 3,
  "age": 4
}

###
POST http://localhost:39148/eai/sendergebnismeldung
Content-Type: application/json

{
  "id": 123,
  "name": "Testname",
  "age": 99,
  "kind": "Schnellmeldung"
}